### ISSUE TITLE
pfinder_init failed on A12X iOS 12.4 unc0ver 3.5.6

### ISSUE THREAD

**Issue by hyln9** [0x7ff/dimentio#1]
Thanks for your great work!

Somehow the program exits after print out kslide and I can confirm pfinder_init failed on my device.

I can provide additional details if needed.

**Comment by kasiimh1** [comment]
Tried this on my iPad Pro 7,3 (A10X) 12.4 a device with KTRR. Same result..

For some reason I couldn't get it to run on my XS on 12.4 kept getting killed:9 even though I had signed the binary with the right entitlements with ldid...

Here is the output from my iPad :

Kasiims-iPad-Pro:/var/mobile/Documents root# ./dimentio 
arm_pgshift: 14
host: 0x1007
tfp0: 0x1603
kbase: 0xffffffe1778b0000
kslide: 0xffc0000

These are the entitlements I am signing the binary with:

	<key>platform-application</key> 

	<true/> 
	<key>com.apple.private.security.container-required</key> 

	<false/> 	
	<key>get-task-allow</key>

	<true/>
	<key>task_for_pid-allow</key>

	<true/>

**Comment by hyln9** [comment]
> Tried this on my iPad Pro 7,3 (A10X) 12.4 a device with KTRR. Same result..
> 
> For some reason I couldn't get it to run on my XS on 12.4 kept getting killed:9 even though I had signed the binary with the right entitlements with ldid...
> 
> Here is the output from my iPad :
> 
> Kasiims-iPad-Pro:/var/mobile/Documents root# ./dimentio
> arm_pgshift: 14
> host: 0x1007
> tfp0: 0x1603
> kbase: 0xffffffe1778b0000
> kslide: 0xffc0000
> 
> These are the entitlements I am signing the binary with:
> 
> ```
> <key>platform-application</key> 
> 
> <true/> 
> <key>com.apple.private.security.container-required</key> 
> 
> <false/> 	
> <key>get-task-allow</key>
> 
> <true/>
> <key>task_for_pid-allow</key>
> 
> <true/>
> ```

Did you have it signed with a CMS blob? Same entitlement here.

**Comment by kasiimh1** [comment]
> > Tried this on my iPad Pro 7,3 (A10X) 12.4 a device with KTRR. Same result..
> > For some reason I couldn't get it to run on my XS on 12.4 kept getting killed:9 even though I had signed the binary with the right entitlements with ldid...
> > Here is the output from my iPad :
> > Kasiims-iPad-Pro:/var/mobile/Documents root# ./dimentio
> > arm_pgshift: 14
> > host: 0x1007
> > tfp0: 0x1603
> > kbase: 0xffffffe1778b0000
> > kslide: 0xffc0000
> > These are the entitlements I am signing the binary with:
> > ```
> > <key>platform-application</key> 
> > 
> > <true/> 
> > <key>com.apple.private.security.container-required</key> 
> > 
> > <false/> 	
> > <key>get-task-allow</key>
> > 
> > <true/>
> > <key>task_for_pid-allow</key>
> > 
> > <true/>
> > ```
> 
> Did you have it signed with a CMS blob? Same entitlement here.

I only signed with ldid using "ldid -Sent.plist "binary" 

Update: ldid -S -M -K/usr/share/jailbreak/signcert.p12 is the command to sign with ent and generate CMS blob? but the signing cert doesn't exist at that path. NVM I extracted the cert from the jailbreaks resources and manually signed the binary again with it

**Comment by hyln9** [comment]
Finally got it partially working after correcting kbase and kslide offsets. The program now prints "Set nonce to 0x1111111111111111" but nvram does not change as desired.

**Comment by hyln9** [comment]
See https://www.reddit.com/r/jailbreak/comments/cyyxzr/tutorial_how_to_set_nonce_generator_for_a12x/ and https://github.com/hyln9/dimentio

**Comment by 0x7ff** [comment]
Hey hyln9,
This is because unc0ver stores cache blob address instead of kernel base in tfp0->all_image_info_addr. I fixed by adding kernel slide into the fixed link address. unc0ver doesn't accept ad-hoc signed binaries because of CoreTrust. unc0ver uses it's own certificate to sign binary by using a ldid wrapper. So I removed codesign from Makefile. You should send dimentio, tfp0.plist into the device and execute "ldid -Stfp0.plist dimentio; ./dimentio nonce" on the device.

**Comment by hyln9** [comment]
Looks like that ldid sign does not work because missing of CMS blob but the offset bug has been fixed, thanks! I've update my tutorial on this.
