### ISSUE TITLE
Compiled latest commit unable to set generator checkra1n and unc0ver 6 with Libkrw

### ISSUE THREAD

**Issue by kasiimh1** [0x7ff/dimentio#11]
Trying to set generator 0x1111111111111111 with 'dementio 0x1111111111111111'

log:
Kasiims-iPhone:~ root# dimentio 0x1111111111111111
boot_path: /private/preboot/92DFB4D9421C6EE6A7619115848B7924B9D5CE965AFFC1F1457A1C86E2F5CC9A1514A336061378BE3EBCBCD391DAE998/System/Library/Caches/com.apple.kernelcaches/kernelcache
base: 0xFFFFFFF007004000
sec_cstring_addr: 0xFFFFFFF007336E54, sec_cstring_off: 0x332E54, sec_cstring_sz: 0x2C47EA
sec_text_addr: 0xFFFFFFF0079D8000, sec_text_off: 0x9D4000, sec_text_sz: 0x1DCF338
cmd_symtab_symoff: 0x0, cmd_symtab_nsyms: 0x0, cmd_symtab_stroff: 0x0
Kasiims-iPhone:~ root# 

This is on the latest unc0ver with libkrw installed.

I have also tried it on my iPad Pro with checkra1n and I get the same log

Does this mean the jailbreak tools themselves haven't added the libkrw support yet?

**Comment by 0x7ff** [comment]
Hey kasiimh1,
Currently the libkrw package only uses the tfp0 method, so it will not work on unc0ver 6 and I believe the issue with checkra1n is due to missing entitlements as it is working on my device.

**Comment by kasiimh1** [comment]
Will check the checkra1n device again along with the entitlements. Thanks for the quick response!

**Comment by kasiimh1** [comment]
Thanks again for your tool, managed to set entitlements and updated to latest unc0ver 6.1.0 and it works correctly.

log:
kasiim@Kasims-iMac ~ % ssh root@192.168.0.11
root@192.168.0.11's password: 
Kasiims-iPhone:~ root# dimentio 0x1111111111111111
boot_path: /private/preboot/92DFB4D9421C6EE6A7619115848B7924B9D5CE965AFFC1F1457A1C86E2F5CC9A1514A336061378BE3EBCBCD391DAE998/System/Library/Caches/com.apple.kernelcaches/kernelcache
base: 0xFFFFFFF007004000
sec_cstring_addr: 0xFFFFFFF007336E54, sec_cstring_off: 0x332E54, sec_cstring_sz: 0x2C47EA
sec_text_addr: 0xFFFFFFF0079D8000, sec_text_off: 0x9D4000, sec_text_sz: 0x1DCF338
cmd_symtab_symoff: 0x0, cmd_symtab_nsyms: 0x0, cmd_symtab_stroff: 0x0
kext_name: com.apple.kec.corecrypto
kext_addr_slid: 0xFFFFFFF0165DED80
kbase: 0xFFFFFFF01542C000, kslide: 0xE428000
kernproc: 0xFFFFFFF015B18568
nvram_entry: 0x1503
our_task: 0xFFFFFFE19FB852C0
nonce_serv: 0x1603
nonce_conn: 0xCCF
itk_space: 0xFFFFFFE1A0D2E1C0
is_table_sz: 0x2A
is_table: 0xFFFFFFE4CB25D000
ipc_port: 0xFFFFFFE1A0317870
nvram_object: 0xFFFFFFE4CDA133C0
of_dict: 0xFFFFFFE19B580A00
os_dict_entry_ptr: 0xFFFFFFE4CD8F3E40
os_dict_cnt: 0xB
key: 0xFFFFFFE19B557F30, val: 0xFFFFFFE1A0BDFD50
cur_key_len: 0x1C
string_ptr: 0xFFFFFFE4CDB4E8C0
os_string: 0xFFFFFFE1A0BDFD50
string_ptr: 0xFFFFFFE4CDCF7F00
aes_serv: 0xCD3
itk_space: 0xFFFFFFE1A0D2E1C0
is_table_sz: 0x2A
is_table: 0xFFFFFFE4CB25D000
ipc_port: 0xFFFFFFE1A0EA4D20
aes_object: 0xFFFFFFE4CD7DC000
keys_ptr: 0xFFFFFFE4CCE2CF00
key_cnt: 0xC
generated: 0x1, key_id: 0x83C, key_sz: 0x80, val: 0x30569A50F8F34B665384881ADCB4B89C
generated: 0x1, key_id: 0x8A4, key_sz: 0x80, val: 0x5F347B83F8210033986171C730AE32CC
generated: 0x1, key_id: 0x8A3, key_sz: 0x80, val: 0xEE1DB667D230558F57C0903D896BC035
Set nonce to 0x1111111111111111
entangled_nonce: B5C76E624A5EAC1D184953190942090E496B948BD9FE1EA1EF88589EB119A350
Kasiims-iPhone:~ root#
