### ISSUE TITLE
Use libkrw_plugin.h to determine if libkrw should be used.

### ISSUE THREAD

**Issue by Halo-Michael** [0x7ff/dimentio#13]
If the function defined in libkrw is used in a jailbreak that does not support libkrw, it will cause an abort:6 error. Therefore, libkrw added a new method to determine whether it is available.
https://github.com/Siguza/libkrw/blob/master/include/libkrw_plugin.h

**Comment by 0x7ff** [comment]
Hey Halo-Michael,
Actually I don't use libkrw.tbd, instead I use dlopen so older versions are still supported. The link you shared with me is for implementing libkrw without creating a new package (unc0ver has created a plugin at /usr/lib/libkrw). If you encountered an issue like an abort, you may create a new issue. Thanks for reporting.

**Comment by Halo-Michael** [comment]
Okey, switch to #14 .
