### ISSUE TITLE
Doesn't work on iOS13

### ISSUE THREAD

**Issue by Halo-Michael** [0x7ff/dimentio#2]
I don't know too much about C, but it seems have issues on init_tfp0().

**Comment by Halo-Michael** [comment]
It's not a issues of dimentio, now close it.

**Comment by Halo-Michael** [comment]
Well, manybe dimentio really should update.

**Comment by Halo-Michael** [comment]
![C33B168D5017C0D2563576090C7A2FD7](https://user-images.githubusercontent.com/45062120/70314667-e82efd80-1852-11ea-9e16-4cdf6e743ce7.png)
Thanks!

**Comment by kasiimh1** [comment]
@0x7ff 

I am also having a problem with Dimentio, i have compiled from latest source (and golb and key_dumper) and ran but it doesn't do much, like before you added you initial fixes for unc0ver.

I am using the latest version of Checkra1n on iOS 13.3 should also mention i am running it on an iPad7,3 (iPad Pro 10.5" WIFI)

```
Kasiims-iPad-Pro:~ root# dimentio 0x1111111111111111
arm_pgshift: 14
host: 0x1503
Kasiims-iPad-Pro:~ root# rm /usr/bin/dimentio
```

*copied over the compiled binary again

```
Kasiims-iPad-Pro:~ root# ldid -S -M /usr/bin/dimentio
Kasiims-iPad-Pro:~ root# dimentio 0x1111111111111111
arm_pgshift: 14
host: 0x1503
Kasiims-iPad-Pro:~ root#
```

Also this isn't the only tool where it is doing this 

golb and key_dumper both do the same

```
Kasiims-iPad-Pro:~ root# golb
arm_pgshift: 14
pmgr_base_off: 0xe000000
aes_ap_base_off: 0xa108000
pmgr_aes0_ps_off: 0x80220
host: 0x1503
```

```
Kasiims-iPad-Pro:~ root# key_dumper
arm_pgshift: 14
host: 0x1503
Kasiims-iPad-Pro:~ root#

```

**Comment by Halo-Michael** [comment]
> @0x7ff
> 
> I am also having a problem with Dimentio, i have compiled from latest source (and golb and key_dumper) and ran but it doesn't do much, like before you added you initial fixes for unc0ver.
> 
> I am using the latest version of Checkra1n on iOS 13.3 should also mention i am running it on an iPad7,3 (iPad Pro 10.5" WIFI)
> 
> ```
> Kasiims-iPad-Pro:~ root# dimentio 0x1111111111111111
> arm_pgshift: 14
> host: 0x1503
> Kasiims-iPad-Pro:~ root# rm /usr/bin/dimentio
> ```
> 
> *copied over the compiled binary again
> 
> ```
> Kasiims-iPad-Pro:~ root# ldid -S -M /usr/bin/dimentio
> Kasiims-iPad-Pro:~ root# dimentio 0x1111111111111111
> arm_pgshift: 14
> host: 0x1503
> Kasiims-iPad-Pro:~ root#
> ```
> 
> Also this isn't the only tool where it is doing this
> 
> golb and key_dumper both do the same
> 
> ```
> Kasiims-iPad-Pro:~ root# golb
> arm_pgshift: 14
> pmgr_base_off: 0xe000000
> aes_ap_base_off: 0xa108000
> pmgr_aes0_ps_off: 0x80220
> host: 0x1503
> ```
> 
> ```
> Kasiims-iPad-Pro:~ root# key_dumper
> arm_pgshift: 14
> host: 0x1503
> Kasiims-iPad-Pro:~ root#
> ```

It sure WORK. If you have any questions, you can check my compiled version: https://halo-michael.github.io/repo/debs/com.michael.dimentio_0.5.0_iphoneos-arm.deb

**Comment by kasiimh1** [comment]
Thanks @Halo-Michael , i just realised it wasn't signing with the entitlements and a valid certificate. Just tried again and both work fine after recompiling! @0x7ff Thanks again for your amazing tool, keep up the good work!
